apiVersion: v1
kind: Service
metadata:
  name: kubernetes-cicd-service
  namespace: kubernetes-cicd
  labels:
    app: kubernetes-cicd-app

spec:
  type: NodePort

  selector:
    app: kubernetes-cicd-app

  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30002
